import img from "./sVwCJQc90UI8g3XF5o_uUX6kQ5lttqBpBsfqDIhkJw70rC3z_NkmQkHrNr+CMlNVtlMdtWyAnWcp+IAMywDRGq6B+08tn28XryN5EzJkaFQvVC2U2sDcW92jtQiS4kKWg5KYA11_xl6rs1cbyLInGHgNk_dtuYuwthu2n1iu_8NYLxCCh_35B9f4AV0C_ZReJepRTY7i3eKcuqd3dmvxbs.png";
const list = [
  {
    id: 1,
    title: "My First Book of Pencil Control",
    author: "by Wonder House Books | 25 April 2018",
    price: 89,
    amount: 1,
    img: img,
  },
  {
    id: 2,
    title: "108 Panchatantra Stories",
    author: "by Maple Press  | 1 September 2020",
    price: 98,
    amount: 1,
    img: img,
  },
  {
    id: 3,
    title: "Amazing Questions & Answers Science",
    author: "by Om Books Editorial Team  | 25 November 2018",
    price: 143,
    amount: 1,
    img: img,
  },
  {
    id: 4,
    title: "My First Book of Pencil Control",
    author: "by Wonder House Books | 25 April 2018",
    price: 57,
    amount: 1,
    img: img,
  },
  {
    id: 5,
    title: "My First 1000 Words",
    author: "by Wonder House Books  | 1 January 2018",
    price: 149,
    amount: 1,
    img: img,
  },
  {
    id: 6,
    title: "101 Panchatantra Stories for Children",
    author: "by Om Books Editorial Team | 30 September 2020",
    price: 135,
    amount: 1,
    img: img,
  },
  {
    id: 7,
    title: "Pre-School Activities Pack ",
    author: "by Om Books Editorial Team  | 1 January 2021",
    price: 693,
    amount: 1,
    img: img,
  },
  {
    id: 8,
    title: "Early Learning Library Pack 1",
    author: "by Wonder House Books  | 6 December 2020",
    price: 289,
    amount: 1,
    img: img,
  },
  {
    id: 9,
    title: "Blossom Moral Story Book for Kids ",
    author: "by Content Team at Target Publications",
    price: 80,
    amount: 1,
    img: img,
  },
  {
    id: 10,
    title: "Brain Activity Book for Kids",
    author: "by Maple Press | 1 September 2021",
    price: 86,
    amount: 1,
    img: img,
  },
  {
    id: 11,
    title: "Willy the Silly Panda",
    author: "by Rebecca Smith  | 14 December 2021",
    price: 120,
    amount: 1,
    img: img,
  },
  {
    id: 12,
    title: "Grandma's Bag of Stories",
    author: "by Sudha Murty | 1 January 2015",
    price: 157,
    amount: 1,
    img: img,
  },
];

export default list;
